name: Update README with Age

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run age script
        run: python3 age_script.py

      - name: Commit changes and push
        run: |
          git config user.name "syartzahiri"
          git config user.email "noreply@github.com"  # Verwende eine generische E-Mail
          git add README.md

